server:
  port: 8804
spring:
  application:
    name: stream-rabbitmq-consumer
  cloud:
    stream:
      #要绑定的消息中间件
      binders:
      #绑定的消息中间件定义的名称 用于binding整合
        defaultRabbit:
          type: rabbit #消息组件类型
          environment: #消息组件的环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #通道名称
          destination: studyExchange  #表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: telecomA
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
  instance:
      lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: send-8804.com  # 在信息列表时显示主机名称
      prefer-ip-address: true     # 访问的路径变为IP地址